# -*- coding: utf-8 -*-
"""EnergyAnalyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrF5OLIPho9-gpaaZLOm76GGUHWJGm3P
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.express as px
from fredapi import Fred
import requests
import os

# -----------------------------
# CONFIG
# -----------------------------
st.set_page_config(page_title="Energy Dashboard MVP", layout="wide")

FRED_API_KEY = "f7619c4dc4477fdbbe78f6e037c00035"
EIA_API_KEY = "hGZAbfuL8LU8EZIbkbwf9Bro7hEh9oepMgrCWM9p"

fred = Fred(api_key=FRED_API_KEY)

# -----------------------------
# HELPERS
# -----------------------------
def yahoo_price(ticker):
    df = yf.download(ticker, period="1y", progress=False)
    if df is None or df.empty:
        return None
    return df["Close"]


def fred_series(series_id):
    return fred.get_series(series_id)

def eia_series(series_id):
    url = f"https://api.eia.gov/v2/{series_id}/data/?api_key={EIA_API_KEY}"
    r = requests.get(url).json()
    df = pd.DataFrame(r["response"]["data"])
    return df

def kpi(label, value, delta=None):
    st.metric(label, value, delta)

# -----------------------------
# SIDEBAR NAV
# -----------------------------
st.sidebar.title("Energy Dashboard MVP")
section = st.sidebar.radio(
    "Navigate",
    ["Executive Summary", "Macroeconomics", "Supply & Demand"]
)

# -----------------------------
# EXEC SUMMARY
# -----------------------------
if section == "Executive Summary":
    st.title("⚡ Executive Summary")

    # Prices
    wti = yahoo_price("CL=F")
    brent = yahoo_price("BZ=F")

    if wti is None or brent is None:
         st.error("Yahoo Finance returned no data. Try again later or check ticker symbols.")
    else:
        col1, col2, col3 = st.columns(3)
        kpi("WTI", f"${wti.iloc[-1]:.2f}", f"{(wti.pct_change().iloc[-1]*100):.2f}%")
        kpi("Brent", f"${brent.iloc[-1]:.2f}", f"{(brent.iloc[-1] - wti.iloc[-1]):.2f}")


    st.markdown("---")
    st.subheader("Price Chart")
    fig = px.line(pd.DataFrame({"WTI": wti, "Brent": brent}))
    st.plotly_chart(fig, use_container_width=True)

# -----------------------------
# MACRO
# -----------------------------
elif section == "Macroeconomics":
    st.title("🌍 Macroeconomics")

    # FRED series
    cpi = fred_series("CPIAUCSL")
    pmi = fred_series("NAPM")
    dxy = yahoo_price("DX-Y.NYB")

    col1, col2, col3 = st.columns(3)
    kpi("US CPI YoY", f"{cpi.pct_change(12).iloc[-1]*100:.2f}%")
    kpi("ISM PMI", f"{pmi.iloc[-1]:.1f}")
    kpi("DXY", f"{dxy.iloc[-1]:.2f}")

    st.markdown("---")
    st.subheader("CPI Chart")
    fig = px.line(cpi, title="US CPI")
    st.plotly_chart(fig, use_container_width=True)

# -----------------------------
# SUPPLY & DEMAND
# -----------------------------
elif section == "Supply & Demand":
    st.title("🛢️ Supply & Demand")

    st.subheader("US Crude Inventories (EIA)")

    # Example EIA endpoint: Weekly US crude stocks
    crude = eia_series("petroleum/stoc/wstk")

    fig = px.line(crude, x="period", y="value", title="US Crude Stocks")
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("US Production (EIA)")
    prod = eia_series("petroleum/pnp/wcrp")

    fig2 = px.line(prod, x="period", y="value", title="US Crude Production")
    st.plotly_chart(fig2, use_container_width=True)